version: '3.8'
services:
  backend:
    build: ./backend
    image: insurebot-backend:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/insurebot
      SPRING_DATASOURCE_USERNAME: your_mysql_userRoot
      SPRING_DATASOURCE_PASSWORD: your_mysql_password
    depends_on:
      - mysql-db
  frontend:
    build: ./frontend
    image: insurebot-frontend:latest
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_BASE_URL: http://localhost:8080/api
    depends_on:
      - backend
  mysql-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: insurebot
      MYSQL_USER: your_mysql_user
      MYSQL_PASSWORD: your_mysql_password
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: 