name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean package --file pom.xml
      - name: Run backend tests
        run: mvn test
      # - name: Build and push Docker image (future)
      #   run: |
      #     docker build -t your-dockerhub-username/insurebot-backend:latest .
      #     echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      #     docker push your-dockerhub-username/insurebot-backend:latest

  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Build frontend
        run: npm run build
      - name: Run frontend tests
        run: npm test
      # - name: Build and push Docker image (future)
      #   run: |
      #     docker build -t your-dockerhub-username/insurebot-frontend:latest .
      #     echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      #     docker push your-dockerhub-username/insurebot-frontend:latest 